"""Parse and validate a story-submission issue, and draft its data.md entry.

Shared with the story-bot workflow. Reuses the pipeline parser/validator
(scripts/datamd.py) so issue submissions face the same rules as PRs.

Usage:
    python3 scripts/story_bot.py --body <issue-body-file> [--root <repo>] [--number N] [--title T] [--write]

Without --write it only validates and prints JSON. With --write it also
appends the drafted entry to data.md (after re-validating the whole
dataset) and writes .story-pr-body.md for the workflow to use.
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

import datamd

ROOT = Path(__file__).resolve().parents[1]

BLOCK_RE = re.compile(r"^### (.+)$")
DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")

REQUIRED_FIELDS = (
    "Article URL",
    "Publication date",
    "Source",
    "AI role",
    "Category",
    "Short factual description",
)


def parse_body(text):
    """Return {section label: value} for the issue-form sections."""
    fields = {}
    current = None
    for line in text.splitlines():
        match = BLOCK_RE.match(line)
        if match:
            current = match.group(1).strip()
            fields[current] = []
            continue
        if current is not None and line.strip():
            fields[current].append(line.strip())
    return {label: "\n".join(lines) for label, lines in fields.items()}


def validate(fields):
    """Validate the parsed form fields; return a list of error strings."""
    errors = []
    for label in REQUIRED_FIELDS:
        if not fields.get(label, "").strip():
            errors.append(f"{label} is missing")
    date_value = fields.get("Publication date", "")
    if date_value:
        if not DATE_RE.fullmatch(date_value):
            errors.append("Publication date must be YYYY-MM-DD")
        else:
            try:
                parsed = datetime.strptime(date_value, "%Y-%m-%d").date()
                if parsed > datetime.now(timezone.utc).date():
                    errors.append("Publication date is in the future")
            except ValueError:
                errors.append("Publication date is not a valid date")
    url = fields.get("Article URL", "")
    if url:
        parsed = urlparse(url)
        if parsed.scheme not in ("http", "https") or not parsed.netloc:
            errors.append("Article URL must be an http(s) URL")
    role = fields.get("AI role", "")
    if role and role not in datamd.ALLOWED_ROLES:
        errors.append(f'AI role must be one of: {", ".join(datamd.ALLOWED_ROLES)}')
    category = fields.get("Category", "")
    if category and category not in datamd.ALLOWED_CATEGORIES:
        errors.append(f"Category must be one of: {', '.join(datamd.ALLOWED_CATEGORIES)}")
    archive = fields.get("Existing Wayback snapshot (optional)", "")
    if archive:
        parsed = urlparse(archive)
        if parsed.scheme not in ("http", "https") or not parsed.netloc:
            errors.append("Archive must be an http(s) URL")
    return errors


def draft_entry(fields, title):
    archive = fields.get("Existing Wayback snapshot (optional)", "").strip()
    archive_line = f"**Archive:** {archive}" if archive else "**Archive:**"
    return f"""---

## {title}

**Date:** {fields['Publication date'].strip()}
**Source:** {fields['Source'].strip()}
**URL:** {fields['Article URL'].strip()}
{archive_line}
**AI role:** {fields['AI role'].strip()}
**Category:** {fields['Category'].strip()}

{fields['Short factual description'].strip()}
"""


def pr_body(fields, title, number):
    rows = [
        ("Date", fields["Publication date"]),
        ("Source", fields["Source"]),
        ("AI role", fields["AI role"]),
        ("Category", fields["Category"]),
    ]
    table = "\n".join(f"| {label} | {value} |" for label, value in rows)
    return f"""Automated draft from story submission #{number}.

{title}

{table}

**Closes #{number}** when merged. Please review before merging:

- [ ] Verified the facts against the source article
- [ ] Date matches the source publication date
- [ ] Free-to-read source preferred over paywalled
- [ ] AI role and category are correctly classified

Generated by `.github/workflows/story-bot.yml` from the issue form answers.
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--body", required=True, help="path to the issue body text")
    parser.add_argument("--root", default=str(ROOT), help="repository root")
    parser.add_argument("--number", type=int, default=0, help="issue number")
    parser.add_argument("--title", default="", help="issue title (draft headline)")
    parser.add_argument("--write", action="store_true", help="append entry to data.md")
    args = parser.parse_args(argv)

    root = Path(args.root)
    fields = parse_body(Path(args.body).read_text(encoding="utf-8"))
    errors = validate(fields)
    if errors:
        print(json.dumps({"ok": False, "errors": errors, "warnings": []}, indent=2))
        return 1

    title = (args.title or fields["Source"] + " incident").strip().splitlines()[0]
    result = {"ok": True, "errors": [], "warnings": [], "title": title}

    if args.write:
        entry = draft_entry(fields, title)
        data_path = root / "data.md"
        candidate = data_path.read_text(encoding="utf-8").rstrip() + "\n" + entry
        entries = datamd.parse_blocks(candidate)
        dataset_errors, warnings = datamd.validate_entries(entries)
        if dataset_errors:
            print(json.dumps({"ok": False, "errors": dataset_errors, "warnings": []}, indent=2))
            return 1
        data_path.write_text(candidate, encoding="utf-8")
        (root / ".story-pr-body.md").write_text(
            pr_body(fields, title, args.number), encoding="utf-8"
        )
        result["warnings"] = warnings

    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())